# Generated by Django 5.0.6 on 2024-06-22 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(max_length=255)),
                ('status_changed_at', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': "       Clients' Statuses",
                'db_table': 'client_statuses',
                'ordering': ['-status_changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('type', models.CharField(max_length=255)),
                ('mode', models.CharField(max_length=255)),
                ('primary_issue_type', models.CharField(max_length=255)),
                ('main_points', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '       Meetings',
                'db_table': 'meetings',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_area', models.TextField()),
                ('industry', models.CharField(max_length=255)),
                ('relation', models.CharField(max_length=255)),
                ('connected_through', models.CharField(max_length=255)),
                ('follow_up_frequency_days', models.IntegerField()),
                ('notes', models.TextField()),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='agent_manager.agent')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '       Clients',
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='client_documents/')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='client_manager.client')),
            ],
            options={
                'verbose_name_plural': "       Clients' Documents",
                'db_table': 'client_documents',
            },
        ),
    ]
