# Generated by Django 5.0.6 on 2024-07-03 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_manager', '0001_initial'),
        ('client_manager', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='agent_manager.agent'),
        ),
        migrations.AlterField(
            model_name='client',
            name='connected_through',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='follow_up_frequency_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='industry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='relation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
