# Generated by Django 5.0.6 on 2024-06-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildata',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
