# Generated by Django 5.0.6 on 2024-06-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_manager', '0002_emaildata_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emaildata',
            options={'ordering': ['-date'], 'verbose_name_plural': '       Emails Data'},
        ),
    ]
