# Generated by Django 5.0.6 on 2024-06-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('date_of_intimation', models.DateTimeField()),
                ('date_of_occurrence', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('cash_call_amount', models.FloatField()),
                ('settlement_amount', models.FloatField()),
            ],
            options={
                'verbose_name_plural': '       Claims',
                'db_table': 'claims',
                'ordering': ['-date_of_intimation'],
            },
        ),
        migrations.CreateModel(
            name='ClaimCredited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('payment_proof', models.FileField(upload_to='claim_credited/')),
            ],
            options={
                'verbose_name_plural': "       Claims' Credits",
                'db_table': 'claims_credited',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ClaimDebited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('payment_proof', models.FileField(upload_to='claim_debited/')),
            ],
            options={
                'verbose_name_plural': "       Claims' Debits",
                'db_table': 'claims_debited',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ClaimDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='claim_documents/')),
            ],
            options={
                'verbose_name_plural': "       Claims' Documents",
                'db_table': 'claim_documents',
            },
        ),
    ]
