# Generated by Django 5.0.6 on 2024-06-22 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claim_manager', '0001_initial'),
        ('risk_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='risk_manager.policy'),
        ),
        migrations.AddField(
            model_name='claimcredited',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crediteds', to='claim_manager.claim'),
        ),
        migrations.AddField(
            model_name='claimcredited',
            name='insurance_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crediteds', to='risk_manager.insuranceline'),
        ),
        migrations.AddField(
            model_name='claimdebited',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debiteds', to='claim_manager.claim'),
        ),
        migrations.AddField(
            model_name='claimdocument',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='claim_manager.claim'),
        ),
    ]
