# Generated by Django 5.0.6 on 2024-07-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim_manager', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='cash_call_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='date_of_intimation',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='date_of_occurrence',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='settlement_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='claimcredited',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='claimcredited',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='claimcredited',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='claim_credited/'),
        ),
        migrations.AlterField(
            model_name='claimdebited',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='claimdebited',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='claimdebited',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='claim_debited/'),
        ),
        migrations.AlterField(
            model_name='claimdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='claim_documents/'),
        ),
        migrations.AlterField(
            model_name='claimdocument',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
