# Generated by Django 5.0.6 on 2024-07-04 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim_manager', '0003_alter_claim_cash_call_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimDebitedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='claims_debited_files/')),
                ('claim_debited', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='claim_manager.claimdebited')),
            ],
            options={
                'verbose_name_plural': '       Claim Debited Files',
                'db_table': 'claims_debited_files',
            },
        ),
    ]
