# Generated by Django 5.0.6 on 2024-07-05 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim_manager', '0004_claimdebitedfile'),
        ('client_manager', '0004_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='client_manager.client'),
        ),
        migrations.AddField(
            model_name='claimdebited',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_debited', to='client_manager.client'),
        ),
    ]
