# Generated by Django 5.0.6 on 2024-07-06 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim_manager', '0005_claim_client_claimdebited_client'),
        ('client_manager', '0004_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_claims', to='client_manager.client'),
        ),
        migrations.AddField(
            model_name='claimdebited',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_claims_debited', to='client_manager.client'),
        ),
    ]
