# Generated by Django 5.0.6 on 2024-07-09 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim_manager', '0006_claim_company_claimdebited_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='claimcredited',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='claimdebited',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='claimdebitedfile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='claimdocument',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 0, 0)),
        ),
    ]
