# Generated by Django 5.0.6 on 2024-07-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim_manager', '0007_claim_created_at_claimcredited_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='claimcredited',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='claimdebited',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='claimdebitedfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='claimdocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
