# Generated by Django 5.0.6 on 2024-06-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('address_area', models.TextField()),
                ('rating', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '       Insurance Companies',
                'db_table': 'insurance_companies',
            },
        ),
    ]
