# Generated by Django 5.0.6 on 2024-06-22 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_manager', '0002_insurancecompany'),
        ('agent_manager', '0001_initial'),
        ('client_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClauseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '       Clause Categories',
                'db_table': 'clause_categories',
            },
        ),
        migrations.CreateModel(
            name='CommissionRealized',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
            ],
            options={
                'verbose_name_plural': '       Commissions Realized',
                'db_table': 'commissions_realized',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField()),
                ('renewal_date', models.DateTimeField()),
                ('number', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='policies/')),
                ('description', models.TextField(blank=True, null=True)),
                ('net_premium', models.FloatField()),
                ('commission_type', models.CharField(max_length=255)),
                ('commission_value', models.FloatField()),
            ],
            options={
                'verbose_name_plural': '       Policies',
                'db_table': 'policies',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='AgentRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenues', to='agent_manager.agent')),
                ('commission_realized', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='risk_manager.commissionrealized')),
            ],
            options={
                'verbose_name_plural': '       Agent Revenues',
                'db_table': 'agent_revenues',
            },
        ),
        migrations.CreateModel(
            name='InsuranceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('policy_number', models.CharField(max_length=255)),
                ('line_written', models.FloatField()),
                ('share_percentage', models.FloatField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('net_premium', models.FloatField()),
                ('insurance_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='account_manager.insurancecompany')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='risk_manager.policy')),
            ],
            options={
                'verbose_name_plural': '       Insurance Lines',
                'db_table': 'insurance_lines',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ImportantClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clauses', to='risk_manager.clausecategory')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clauses', to='risk_manager.policy')),
            ],
            options={
                'verbose_name_plural': '       Important Clauses',
                'db_table': 'important_clauses',
            },
        ),
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('new_renewal_date', models.DateTimeField()),
                ('number', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='endorsements/')),
                ('description', models.TextField(blank=True, null=True)),
                ('new_net_premium', models.FloatField()),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endorsements', to='risk_manager.policy')),
            ],
            options={
                'verbose_name_plural': '       Endorsements',
                'db_table': 'endorsements',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='commissionrealized',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='risk_manager.policy'),
        ),
        migrations.CreateModel(
            name='PremiumCredited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('payment_proof', models.FileField(upload_to='premium_credited/')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crediteds', to='risk_manager.policy')),
            ],
            options={
                'verbose_name_plural': '       Premiums Credited',
                'db_table': 'premiums_credited',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='commissionrealized',
            name='premium_credited',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission', to='risk_manager.premiumcredited'),
        ),
        migrations.CreateModel(
            name='PremiumDebited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('payment_proof', models.FileField(upload_to='premium_debited/')),
                ('insurance_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debiteds', to='risk_manager.insuranceline')),
            ],
            options={
                'verbose_name_plural': '       Premiums Debited',
                'db_table': 'premiums_debited',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('quoted_rate', models.FloatField()),
                ('line_written', models.FloatField()),
                ('share_percentage', models.FloatField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('insurance_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='account_manager.insurancecompany')),
            ],
            options={
                'verbose_name_plural': '       Quotations',
                'db_table': 'quotations',
            },
        ),
        migrations.CreateModel(
            name='QuotationClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qlauses', to='risk_manager.clausecategory')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qlauses', to='risk_manager.quotation')),
            ],
            options={
                'verbose_name_plural': '       Quotation Clauses',
                'db_table': 'quotation_clauses',
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_insured', models.FloatField()),
                ('type', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='client_manager.client')),
            ],
            options={
                'verbose_name_plural': '       Risks',
                'db_table': 'risks',
            },
        ),
        migrations.AddField(
            model_name='quotation',
            name='risk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='risk_manager.risk'),
        ),
        migrations.AddField(
            model_name='policy',
            name='risk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='risk_manager.risk'),
        ),
    ]
