# Generated by Django 5.0.6 on 2024-06-25 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='policy_files/')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='risk_manager.policy')),
            ],
            options={
                'verbose_name_plural': '       Policy Files',
                'db_table': 'policy_files',
            },
        ),
    ]
