# Generated by Django 5.0.6 on 2024-07-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_manager', '0002_policyfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='policy_files/'),
        ),
        migrations.AlterField(
            model_name='policyfile',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
