# Generated by Django 5.0.6 on 2024-07-03 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_manager', '0004_alter_policy_commission_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumCreditedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='premium_credited_files/')),
                ('premium_credited', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='risk_manager.premiumcredited')),
            ],
            options={
                'verbose_name_plural': '       Premium Credited Files',
                'db_table': 'premium_credited_files',
            },
        ),
    ]
