# Generated by Django 5.0.6 on 2024-07-03 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_manager', '0005_premiumcreditedfile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='premiumcreditedfile',
            table='premiums_credited_files',
        ),
    ]
