# Generated by Django 5.0.6 on 2024-07-05 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_manager', '0004_client_name'),
        ('risk_manager', '0007_alter_premiumcreditedfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='client_manager.client'),
        ),
        migrations.AddField(
            model_name='premiumcredited',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premiums_credited', to='client_manager.client'),
        ),
    ]
