# Generated by Django 5.0.6 on 2024-07-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_manager', '0008_policy_client_premiumcredited_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='sum_insured',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
