# Generated by Django 5.0.6 on 2024-07-06 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_manager', '0004_client_name'),
        ('risk_manager', '0009_alter_risk_sum_insured_alter_risk_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_policies', to='client_manager.client'),
        ),
        migrations.AddField(
            model_name='premiumcredited',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_premiums_credited', to='client_manager.client'),
        ),
        migrations.AddField(
            model_name='risk',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_risks', to='client_manager.client'),
        ),
    ]
