# Generated by Django 5.0.6 on 2024-07-09 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_manager', '0010_policy_company_premiumcredited_company_risk_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='policyfile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='premiumcredited',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='premiumcreditedfile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='risk',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 0, 0)),
        ),
    ]
