# Generated by Django 5.0.6 on 2024-07-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_manager', '0012_alter_policy_created_at_alter_policyfile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='file',
            field=models.FileField(null=True, upload_to='policies/'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
